name: catty

services:
  app:
    image: ${APP_IMAGE:-ghcr.io/vichurinnik/catty-reminders-app:latest}
    container_name: catty-app
    restart: unless-stopped
    environment:
      - DEPLOY_REF=${DEPLOY_REF}
    ports:
      - "8181:8181"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./reminder_db.json:/app/reminder_db.json
    networks:
      - catty-network

networks:
  catty-network:
    driver: bridge
