name: Deploy

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare lowercase repo name
        run: echo "REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image with DEPLOY_REF
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}:latest
            ghcr.io/${{ env.REPO_LOWER }}:${{ github.sha }}
          build-args: |
            DEPLOY_REF=${{ github.sha }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: course.prafdin.ru
          username: vboxuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 3106
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ env.REPO_LOWER }}:latest
            docker stop catty-app || true
            docker rm catty-app || true
            docker run -d \
              --name catty-app \
              -p 8181:8181 \
              --restart always \
              -e DEPLOY_REF="${{ github.sha }}" \
              ghcr.io/${{ env.REPO_LOWER }}:latest
